# Generated by Django 6.0.2 on 2026-03-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_outline",
            field=models.FileField(blank=True, null=True, upload_to="course_outlines/"),
        ),
    ]
