# Generated by Django 6.0.2 on 2026-03-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_missing_course_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_courses', to='main.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='rep_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
    ]
