# Generated by Django 6.0.2 on 2026-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_course_parent_course_alter_course_classroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_lab",
            field=models.BooleanField(default=False),
        ),
    ]
