# Generated by Django 6.0.2 on 2026-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_is_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
