# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_backendlog_errorreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to=main.models.snap_upload_path)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all_friends", "All friends"),
                            ("selected", "Selected friends"),
                        ],
                        default="all_friends",
                        max_length=16,
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snaps",
                        to="main.course",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="main.snap",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snap_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["viewer", "has_viewed"],
                        name="main_snapau_viewer__bfe1f0_idx",
                    )
                ],
                "unique_together": {("snap", "viewer")},
            },
        ),
        migrations.AddIndex(
            model_name="snap",
            index=models.Index(
                fields=["course", "expires_at", "is_removed"],
                name="main_snap_course__c84a4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="snap",
            index=models.Index(
                fields=["uploader", "created_at"],
                name="main_snap_uploade_2b6d70_idx",
            ),
        ),
    ]
