# Generated by Django 6.0.2 on 2026-05-20 08:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_moderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snap",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all_friends", "All friends"),
                    ("selected", "Selected friends"),
                    ("group", "Snap group"),
                ],
                default="all_friends",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snaps_from_friends", models.BooleanField(default=True)),
                ("class_is_live", models.BooleanField(default=True)),
                ("weekly_recap", models.BooleanField(default=False)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(default=datetime.time(22, 0))),
                ("quiet_hours_end", models.TimeField(default=datetime.time(8, 0))),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noti_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snap_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="main.snapgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snap_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="snapgroup",
            index=models.Index(
                fields=["owner", "-updated_at"], name="main_snapgr_owner_i_e4263d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapgroupmember",
            index=models.Index(
                fields=["group", "user"], name="main_snapgr_group_i_a4aa72_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="snapgroupmember",
            unique_together={("group", "user")},
        ),
    ]
