# Generated by Django 6.0.2 on 2026-05-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_settings_and_snap_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="replied_snap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies_in_chat",
                to="main.snap",
            ),
        ),
    ]
