# Generated by Django 6.0.2 on 2026-06-05 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_reparselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('study_invite', 'Study invite')], default='text', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExternalCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Busy', max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_blocking', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('study_invite', 'Study invite'), ('manual', 'Manual'), ('external', 'External calendar')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'starts_at', 'ends_at'], name='main_extern_user_id_dd0d7f_idx')],
            },
        ),
    ]
