# Generated by Django 6.0.2 on 2026-06-05 16:43

from django.db import migrations, models


def migrate_semi_to_private(apps, schema_editor):
    """SEMI was a v1 placeholder that behaved like PRIVATE. Collapse any
    existing rows to PRIVATE so the constrained choice list still validates."""
    Event = apps.get_model("main", "Event")
    Event.objects.filter(visibility="SEMI").update(visibility="PRIVATE")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_event_eventinvite_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_semi_to_private, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("PRIVATE", "Private"), ("PUBLIC", "Public")],
                default="PRIVATE",
                max_length=8,
            ),
        ),
    ]
