# Generated by Django 6.0.2 on 2026-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_drop_event_semi_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_join_requests",
            field=models.BooleanField(default=False),
        ),
    ]
