# Generated by Django 6.0.2 on 2026-06-19 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_eventinvite_requested_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinvite",
            name="skip_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("skip", "Skip clashing block"),
                    ("keep_both", "Keep both"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="CourseSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skips",
                        to="main.course",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_skips",
                        to="main.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_skips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="main_course_user_id_b943cc_idx"
                    )
                ],
                "unique_together": {("user", "course", "date")},
            },
        ),
        migrations.CreateModel(
            name="EventOccurrenceSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attending_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_skips",
                        to="main.event",
                    ),
                ),
                (
                    "skipped_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrence_skips",
                        to="main.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_skips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="main_evento_user_id_ed7bc8_idx"
                    )
                ],
                "unique_together": {("user", "skipped_event", "date")},
            },
        ),
    ]
