# Generated by Django 6.0.2 on 2026-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_eventinvite_skip_preference_courseskip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("study_invite", "Study invite"),
                    ("event_card", "Event card"),
                ],
                default="text",
                max_length=16,
            ),
        ),
    ]
