# Generated by Django 6.0.2 on 2026-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_customuser_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
