# Generated by Django 6.0.2 on 2026-07-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_customuser_pending_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="invite_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=22, null=True, unique=True
            ),
        ),
    ]
