# Generated by Django 6.0.2 on 2026-07-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_customuser_invite_code"),
        ("main", "0030_seed_first_blog_post"),
    ]

    operations = []
