# Generated by Django 6.0.2 on 2026-08-14 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_merge_20260717_0105"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("window_started_at", models.DateTimeField(blank=True, null=True)),
                ("window_count", models.PositiveIntegerField(default=0)),
                (
                    "write_window_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("write_window_count", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="main_agenta_user_id_8f33fa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentPendingWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("tool", models.CharField(max_length=64)),
                ("payload_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("result_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_pending_writes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="main_agentp_user_id_fd933d_idx",
                    )
                ],
            },
        ),
    ]
