# Generated by Django 6.0.7 on 2026-09-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="date_is_estimate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="date_is_estimate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
