from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('api/register/', views.RegisterView.as_view(), name='register'),
    path('api/login/', views.LoginView.as_view(), name='login'),
    path('api/courses/', views.CourseListCreateView.as_view(), name='course-list'),
    path('api/courses/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('api/weeks/', views.WeekListCreateView.as_view(), name='week-list'),
    path('api/weeks/<int:pk>/', views.WeekDetailView.as_view(), name='week-detail'),
    path('api/exams/', views.ExamListCreateView.as_view(), name='exam-list'),
    path('api/exams/<int:pk>/', views.ExamDetailView.as_view(), name='exam-detail'),
    path('api/assignments/', views.AssignmentListCreateView.as_view(), name='assignment-list'),
    path('api/assignments/<int:pk>/', views.AssignmentDetailView.as_view(), name='assignment-detail'),
    path('api/friend-requests/', views.FriendRequestView.as_view(), name='friend-request-create'),
    path('api/friend-requests/pending/', views.FriendRequestListView.as_view(), name='friend-requests-pending'),
    path('api/friend-requests/<int:pk>/', views.FriendRequestUpdateView.as_view(), name='friend-request-update'),
    path('api/friends/', views.FriendListView.as_view(), name='friends-list'),
    path('api/friends/search/', views.SearchFriend.as_view(), name='search-friend'), 
    path('api/user/', views.get_user, name='user'), 
    path('api/test-email/', views.TestEmailView.as_view(), name='test-email'),
    path('api/report-error/', views.ErrorReportView.as_view(), name='report-error'),
    path('api/courses/analyze/', views.CourseAnalyzeView.as_view(), name='course-analyze'),
    path('api/courses/finalize/', views.CourseFinalizeView.as_view(), name='course-finalize'),
    path('api/snaps/', views.SnapUploadView.as_view(), name='snap-upload'),
    path('api/snaps/feed/', views.SnapFeedView.as_view(), name='snap-feed'),
    path('api/snaps/<int:pk>/view/', views.SnapViewView.as_view(), name='snap-view'),
    path('api/snaps/<int:pk>/', views.SnapDeleteView.as_view(), name='snap-delete'),
    path('api/notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('api/chats/', views.ChatListCreateView.as_view(), name='chat-list-create'),
    path('api/chats/unread/', views.UnreadCountView.as_view(), name='chat-unread'),
    path('api/chats/<int:pk>/', views.ChatDetailView.as_view(), name='chat-detail'),
    path('api/chats/<int:pk>/read/', views.ChatReadView.as_view(), name='chat-read'),
    path('api/chats/<int:pk>/messages/', views.MessageListCreateView.as_view(), name='chat-messages'),
    path('api/chats/<int:pk>/messages/<int:msg_id>/', views.MessageDeleteView.as_view(), name='chat-message-delete'),
]